version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: .dockerfile
    image: 'postgres:latest'
    container_name: libraryapi-db
    restart: unless-stopped
    tty: true
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/libraryapi
    volumes:
      - libraryapi:/var/lib/postgresql/data

volumes:
  libraryapi:
